### ISSUE TITLE
并发控制器

### ISSUE THREAD

**Issue by YuYang019** [ies-fe-sh/hire#2]
希望任务描述能补充下 `PromiseConcurrencyController` 在不同场景下的调用方式，伪代码就行，不然光凭文字有点抽象呢。。写出来的不符合题意，不知道是不是我语文不好 orz

**Comment by Brooooooklyn** [comment]
实现 index.ts 里面的几个方法就好了，是需要补充注释到方法那里吗？

**Comment by YuYang019** [comment]
好的👌
